const IMAGE_DATA = {};

const categories = [
  ['Salatlar', 'cat-salads', 'salads'],
  ['Gazaklar', 'cat-starters', 'starters'],
  ['Sho‘rvalar', 'cat-soups', 'soups'],
  ['Mangal va kaboblar', 'cat-grill', 'grill'],
  ['Baliq taomlari', 'cat-fish', 'fish'],
  ['Xamirli taomlar', 'cat-dough', 'dough'],
  ['Asosiy taomlar', 'cat-main', 'main'],
  ['Katta assortilar', 'cat-platters', 'platters'],
  ['Desert va mevalar', 'cat-desserts', 'desserts'],
  ['Garnir va sabzavot', 'cat-garnish', 'garnish'],
];

const menuCatalog = [
  { cat: 'salads', img: '04_Achik_Chuchuk.jpg', uz: 'Achchiq-chuchuk', ru: 'Ачик-чучук', en: 'Achik-Chuchuk' },
  { cat: 'salads', img: '10_Burrata_pomidor_bilan.jpg', uz: 'Burrata pomidor bilan', ru: 'Буррата с помидорами', en: 'Burrata with Tomatoes' },
  { cat: 'salads', img: '13_Vitamin_salat.jpg', uz: 'Vitamin salat', ru: 'Витаминный салат', en: 'Vitamin Salad' },
  { cat: 'salads', img: '16_Grek_salat.jpg', uz: 'Grek salat', ru: 'Греческий салат', en: 'Greek Salad' },
  { cat: 'salads', img: '20_Kukaldosh_salat_1.jpg', uz: 'Kukaldosh salat №1', ru: 'Салат «Кукалдош» №1', en: 'Kukaldosh Salad No. 1' },
  { cat: 'salads', img: '21_Kukaldosh_salat_2.jpg', uz: 'Kukaldosh salat №2', ru: 'Салат «Кукалдош» №2', en: 'Kukaldosh Salad No. 2' },
  { cat: 'salads', img: '25_Livancha_Tabule_salat.jpg', uz: 'Livancha tabule salat', ru: 'Ливанский салат табуле', en: 'Lebanese Tabbouleh Salad' },
  { cat: 'salads', img: '32_Erkaklar_injiqligi_salat.jpg', uz: 'Erkaklar injiqligi salati', ru: 'Салат «Мужской каприз»', en: "Men's Caprice Salad" },
  { cat: 'salads', img: '35_Olivye_salat.jpg', uz: 'Olivye salat', ru: 'Салат оливье', en: 'Olivier Salad' },
  { cat: 'salads', img: '37_Rukkola_apelsin_bilan.jpg', uz: 'Rukkola apelsin bilan', ru: 'Руккола с апельсином', en: 'Arugula with Orange' },
  { cat: 'salads', img: '38_Qo_ziqorinli_salat.jpg', uz: 'Qo‘ziqorinli salat', ru: 'Салат с грибами', en: 'Mushroom Salad' },
  { cat: 'salads', img: '39_Okean_salat.jpg', uz: 'Okean salat', ru: 'Салат «Океан»', en: 'Ocean Salad' },
  { cat: 'salads', img: '44_Xorovats.jpg', uz: 'Xorovats', ru: 'Хоровац', en: 'Khorovats' },
  { cat: 'salads', img: '45_Qarsildoq_baqlajon.jpg', uz: 'Qarsildoq baqlajon', ru: 'Хрустящий баклажан', en: 'Crispy Eggplant' },
  { cat: 'salads', img: '46_Qarsildoq_yashil_salat.jpg', uz: 'Qarsildoq yashil salat', ru: 'Хрустящий зелёный салат', en: 'Crispy Green Salad' },
  { cat: 'salads', img: '47_Sezar_salat.jpg', uz: 'Sezar salat', ru: 'Салат «Цезарь»', en: 'Caesar Salad' },
  { cat: 'salads', img: '50_Chuponcha_salat.jpg', uz: 'Cho‘poncha salat', ru: 'Салат «Чупонча»', en: "Shepherd's Salad" },
  { cat: 'salads', img: '51_Shakarob_salat.jpg', uz: 'Shakarob salat', ru: 'Салат шакароб', en: 'Shakarob Salad' },

  { cat: 'starters', img: '33_Go_sht_assorti.jpg', uz: 'Go‘sht assorti', ru: 'Мясное ассорти', en: 'Meat Platter' },
  { cat: 'starters', img: '40_Ruscha_seld.jpg', uz: 'Ruscha seld', ru: 'Сельдь по-русски', en: 'Russian Herring' },
  { cat: 'starters', img: '41_Suzma.jpg', uz: 'Suzma', ru: 'Сузьма', en: 'Suzma' },
  { cat: 'starters', img: '42_Pishloq_assorti.jpg', uz: 'Pishloq assorti', ru: 'Сырное ассорти', en: 'Cheese Platter' },
  { cat: 'starters', img: '49_Chilla.jpg', uz: 'Chilla', ru: 'Чилла', en: 'Chilla' },

  { cat: 'soups', img: '09_Borsh.jpg', uz: 'Borsh', ru: 'Борщ', en: 'Borscht' },
  { cat: 'soups', img: '19_Yasmiq_krem_shorva.jpg', uz: 'Yasmiq krem sho‘rva', ru: 'Крем-суп из чечевицы', en: 'Lentil Cream Soup' },
  { cat: 'soups', img: '22_Tovuqli_ugra_shorva.jpg', uz: 'Tovuqli ugra sho‘rva', ru: 'Куриный суп с лапшой', en: 'Chicken Noodle Soup' },
  { cat: 'soups', img: '31_Mastava.jpg', uz: 'Mastava', ru: 'Мастава', en: 'Mastava' },
  { cat: 'soups', img: '53_Qaynatma_shorva.jpg', uz: 'Qaynatma sho‘rva', ru: 'Суп «Кайнатма»', en: 'Qaynatma Soup' },
  { cat: 'soups', img: '54_Shi_shorva.jpg', uz: 'Shi sho‘rva', ru: 'Щи', en: 'Shchi Soup' },

  { cat: 'grill', img: '05_Qo_zi_qovurg_asi_0_5kg.jpg', uz: 'Qo‘zi qovurg‘asi, 0.5 kg', ru: 'Бараньи рёбра, 0.5 кг', en: 'Lamb Ribs, 0.5 kg' },
  { cat: 'grill', img: '06_BBQ_qo_zi_qovurg_asi_0_5kg.jpg', uz: 'BBQ qo‘zi qovurg‘asi, 0.5 kg', ru: 'Бараньи рёбра BBQ, 0.5 кг', en: 'BBQ Lamb Ribs, 0.5 kg' },
  { cat: 'grill', img: '08_Mangalda_mol_filesi_100g.jpg', uz: 'Mangalda mol filesi, 100 g', ru: 'Говяжье филе на мангале, 100 г', en: 'Grilled Beef Fillet, 100 g' },
  { cat: 'grill', img: '15_Mangalda_mol_tili_100g.jpg', uz: 'Mangalda mol tili, 100 g', ru: 'Говяжий язык на мангале, 100 г', en: 'Grilled Beef Tongue, 100 g' },
  { cat: 'grill', img: '23_Mangalda_tovuq_500g.jpg', uz: 'Mangalda tovuq, 500 g', ru: 'Курица на мангале, 500 г', en: 'Grilled Chicken, 500 g' },
  { cat: 'grill', img: '28_Lyulya_kabob.jpg', uz: 'Lyulya kabob', ru: 'Люля-кебаб', en: 'Lula Kebab' },
  { cat: 'grill', img: '48_Mol_chalagach_100g.jpg', uz: 'Mol chalag‘ach, 100 g', ru: 'Чалагач из говядины, 100 г', en: 'Beef Chalaghach, 100 g' },
  { cat: 'grill', img: '52_Qo_zi_jigari_shashlik.jpg', uz: 'Qo‘zi jigari shashlik', ru: 'Шашлык из бараньей печени', en: 'Lamb Liver Shashlik' },

  { cat: 'fish', img: '18_Qovurilgan_sudak_0_5kg.jpg', uz: 'Qovurilgan sudak, 0.5 kg', ru: 'Жареный судак, 0.5 кг', en: 'Fried Pike-Perch, 0.5 kg' },
  { cat: 'fish', img: '26_Losos_shampurda_1_dona.jpg', uz: 'Losos shampurda, 1 dona', ru: 'Лосось на шампуре, 1 шт.', en: 'Skewered Salmon, 1 pc' },
  { cat: 'fish', img: '27_Losos_sitrus_miksi_bilan.jpg', uz: 'Losos sitrus miksi bilan', ru: 'Лосось с цитрусовым миксом', en: 'Salmon with Citrus Mix' },

  { cat: 'dough', img: '01_Alat_samsa_go_shtli.jpg', uz: 'Alat somsasi, go‘shtli', ru: 'Самса «Алат» с мясом', en: 'Alat Meat Samsa' },
  { cat: 'dough', img: '07_Bichak_ko_kat_yoki_qovoqli.jpg', uz: 'Bichak, ko‘kat yoki qovoqli', ru: 'Бичак с зеленью или тыквой', en: 'Bichak with Herbs or Pumpkin' },
  { cat: 'dough', img: '29_Manti_Gurman_3_dona.jpg', uz: 'Manti «Gurman», 3 dona', ru: 'Манты «Гурман», 3 шт.', en: 'Gurman Manti, 3 pcs' },
  { cat: 'dough', img: '30_Manti_Podshoh_sovg_asi_3_dona.jpg', uz: 'Manti «Podshoh sovg‘asi», 3 dona', ru: 'Манты «Подарок падишаха», 3 шт.', en: "Royal Gift Manti, 3 pcs" },
  { cat: 'dough', img: '43_Tandir_samsa_mol_go_shtli.jpg', uz: 'Tandir somsa, mol go‘shtli', ru: 'Тандырная самса с говядиной', en: 'Tandoor Beef Samsa' },

  { cat: 'main', img: '11_Buxorocha_jiz_mol_filesi.jpg', uz: 'Buxorocha jiz, mol filesi', ru: 'Бухарский джиз из говяжьего филе', en: 'Bukhara-Style Beef Jiz' },
  { cat: 'main', img: '12_Qo_zi_vagurri.jpg', uz: 'Qo‘zi vagurri', ru: 'Вагурри из баранины', en: 'Lamb Vagurri' },
  { cat: 'main', img: '17_Dolma_7_dona.jpg', uz: 'Dolma, 7 dona', ru: 'Долма, 7 шт.', en: 'Dolma, 7 pcs' },
  { cat: 'main', img: '24_Kurtoba.jpg', uz: 'Qurtoba', ru: 'Куртоба', en: 'Qurtoba' },

  { cat: 'platters', img: '03_Shoxona_assorti.jpg', uz: 'Shohona assorti', ru: 'Ассорти «Шохона»', en: 'Royal Platter' },
  { cat: 'platters', img: '36_Erkaklar_bazmi_4_6_kishi.jpg', uz: 'Erkaklar bazmi, 4–6 kishi', ru: 'Мужской пир, на 4–6 человек', en: "Men's Feast, for 4–6" },

  { cat: 'desserts', img: '02_Tarvuz_mavsumiy.jpg', uz: 'Tarvuz, mavsumiy', ru: 'Арбуз, сезонный', en: 'Watermelon, Seasonal' },
  { cat: 'desserts', img: '14_Sharqona_shirinliklar_assorti.jpg', uz: 'Sharqona shirinliklar assorti', ru: 'Ассорти восточных сладостей', en: 'Oriental Sweets Platter' },

  { cat: 'garnish', img: '34_Mangalda_sabzavotlar.jpg', uz: 'Mangalda sabzavotlar', ru: 'Овощи на мангале', en: 'Grilled Vegetables' },
];

const menuPrices = {
  '01_Alat_samsa_go_shtli.jpg': '60 000 so‘m',
  '02_Tarvuz_mavsumiy.jpg': '40 000 so‘m',
  '03_Shoxona_assorti.jpg': '1 050 000 so‘m',
  '04_Achik_Chuchuk.jpg': '40 000 so‘m',
  '05_Qo_zi_qovurg_asi_0_5kg.jpg': '210 000 so‘m',
  '06_BBQ_qo_zi_qovurg_asi_0_5kg.jpg': '225 000 so‘m',
  '07_Bichak_ko_kat_yoki_qovoqli.jpg': '40 000 so‘m',
  '08_Mangalda_mol_filesi_100g.jpg': '55 000 so‘m',
  '09_Borsh.jpg': '50 000 so‘m',
  '10_Burrata_pomidor_bilan.jpg': '100 000 so‘m',
  '11_Buxorocha_jiz_mol_filesi.jpg': '230 000 so‘m',
  '12_Qo_zi_vagurri.jpg': '200 000 so‘m',
  '13_Vitamin_salat.jpg': '40 000 so‘m',
  '14_Sharqona_shirinliklar_assorti.jpg': '75 000 so‘m',
  '15_Mangalda_mol_tili_100g.jpg': '55 000 so‘m',
  '16_Grek_salat.jpg': '60 000 so‘m',
  '17_Dolma_7_dona.jpg': '50 000 so‘m',
  '18_Qovurilgan_sudak_0_5kg.jpg': '170 000 so‘m',
  '19_Yasmiq_krem_shorva.jpg': '35 000 so‘m',
  '20_Kukaldosh_salat_1.jpg': '85 000 so‘m',
  '21_Kukaldosh_salat_2.jpg': '85 000 so‘m',
  '22_Tovuqli_ugra_shorva.jpg': '40 000 so‘m',
  '23_Mangalda_tovuq_500g.jpg': '80 000 so‘m',
  '24_Kurtoba.jpg': '310 000 so‘m',
  '25_Livancha_Tabule_salat.jpg': '55 000 so‘m',
  '26_Losos_shampurda_1_dona.jpg': '80 000 so‘m',
  '27_Losos_sitrus_miksi_bilan.jpg': '140 000 so‘m',
  '28_Lyulya_kabob.jpg': '75 000 so‘m',
  '29_Manti_Gurman_3_dona.jpg': '40 000 so‘m',
  '30_Manti_Podshoh_sovg_asi_3_dona.jpg': '45 000 so‘m',
  '31_Mastava.jpg': '50 000 so‘m',
  '32_Erkaklar_injiqligi_salat.jpg': '80 000 so‘m',
  '33_Go_sht_assorti.jpg': '220 000 so‘m',
  '34_Mangalda_sabzavotlar.jpg': '40 000 so‘m',
  '35_Olivye_salat.jpg': '50 000 so‘m',
  '36_Erkaklar_bazmi_4_6_kishi.jpg': '900 000 so‘m',
  '37_Rukkola_apelsin_bilan.jpg': '90 000 so‘m',
  '38_Qo_ziqorinli_salat.jpg': '50 000 so‘m',
  '39_Okean_salat.jpg': '85 000 so‘m',
  '40_Ruscha_seld.jpg': '70 000 so‘m',
  '41_Suzma.jpg': '30 000 so‘m',
  '42_Pishloq_assorti.jpg': '200 000 so‘m',
  '43_Tandir_samsa_mol_go_shtli.jpg': '20 000 so‘m',
  '44_Xorovats.jpg': '40 000 so‘m',
  '45_Qarsildoq_baqlajon.jpg': '80 000 so‘m',
  '46_Qarsildoq_yashil_salat.jpg': '45 000 so‘m',
  '47_Sezar_salat.jpg': '70 000 so‘m',
  '48_Mol_chalagach_100g.jpg': '45 000 so‘m',
  '49_Chilla.jpg': '65 000 so‘m',
  '50_Chuponcha_salat.jpg': '45 000 so‘m',
  '51_Shakarob_salat.jpg': '40 000 so‘m',
  '52_Qo_zi_jigari_shashlik.jpg': '35 000 so‘m',
  '53_Qaynatma_shorva.jpg': '50 000 so‘m',
  '54_Shi_shorva.jpg': '35 000 so‘m',
};

const russianDescriptions = {
  salads: 'Свежий салат из отборных ингредиентов.',
  starters: 'Закуска для лёгкого и аппетитного начала.',
  soups: 'Ароматный суп по фирменному рецепту.',
  grill: 'Блюдо, приготовленное на открытом огне.',
  fish: 'Рыбное блюдо из свежих ингредиентов.',
  dough: 'Традиционное блюдо из тонкого теста.',
  main: 'Сытное основное блюдо от шеф-повара.',
  platters: 'Большое ассорти для тёплой компании.',
  desserts: 'Сладкое завершение семейной трапезы.',
  garnish: 'Свежеприготовленный гарнир к столу.',
};

const products = menuCatalog.map((item) => ({
  cat: item.cat,
  img: `assets/menu/${item.img}`,
  price: menuPrices[item.img],
  name: item.ru,
  desc: russianDescriptions[item.cat],
}));

const productNames = {
  uz: menuCatalog.map((item) => item.uz),
  en: menuCatalog.map((item) => item.en),
};

const ui = {
  ru: {
    address: 'г. Бухара, улица Эшони Пир, дом 11',
    search: 'Поиск блюда...',
    count: (n) => `${n} блюд`,
    desc: russianDescriptions,
  },
  uz: {
    address: 'Buxoro shahri, Eshoni Pir ko‘chasi, 11-uy',
    search: 'Taom nomini qidiring...',
    count: (n) => `${n} ta taom`,
    desc: {
      salads: 'Saralangan masalliqlardan tayyorlangan yangi salat.',
      starters: 'Dasturxon uchun yengil va mazali gazak.',
      soups: 'Maxsus retsept asosidagi xushbo‘y sho‘rva.',
      grill: 'Ochiq olovda mahorat bilan pishirilgan taom.',
      fish: 'Yangi masalliqlardan tayyorlangan baliq taomi.',
      dough: 'Yupqa xamirdan tayyorlangan an’anaviy taom.',
      main: 'Oshpazimiz tayyorlagan to‘yimli asosiy taom.',
      platters: 'Davralar uchun mo‘l-ko‘l katta assorti.',
      desserts: 'Oilaviy taomni yakunlovchi shirinlik.',
      garnish: 'Dasturxon uchun yangi tayyorlangan garnir.',
    },
  },
  en: {
    address: '11 Eshoni Pir Street, Bukhara',
    search: 'Search dishes...',
    count: (n) => `${n} dishes`,
    desc: {
      salads: 'A fresh salad made with selected ingredients.',
      starters: 'A light and flavorful start to the meal.',
      soups: 'An aromatic soup prepared to our signature recipe.',
      grill: 'A dish skillfully cooked over an open flame.',
      fish: 'A fish dish prepared with fresh ingredients.',
      dough: 'A traditional dish made with delicate dough.',
      main: 'A satisfying main course prepared by our chef.',
      platters: 'A generous platter made for sharing.',
      desserts: 'A sweet finish to a family meal.',
      garnish: 'A freshly prepared side dish for the table.',
    },
  },
};

const categoryNames = {
  salads: { ru: 'Салаты', uz: 'Salatlar', en: 'Salads' },
  starters: { ru: 'Закуски', uz: 'Gazaklar', en: 'Appetizers' },
  soups: { ru: 'Супы', uz: 'Sho‘rvalar', en: 'Soups' },
  grill: { ru: 'Мангал и шашлыки', uz: 'Mangal va kaboblar', en: 'Grill & Kebabs' },
  fish: { ru: 'Рыбные блюда', uz: 'Baliq taomlari', en: 'Fish Dishes' },
  dough: { ru: 'Блюда из теста', uz: 'Xamirli taomlar', en: 'Dough Dishes' },
  main: { ru: 'Основные блюда', uz: 'Asosiy taomlar', en: 'Main Courses' },
  platters: { ru: 'Большие ассорти', uz: 'Katta assortilar', en: 'Large Platters' },
  desserts: { ru: 'Десерты и фрукты', uz: 'Desert va mevalar', en: 'Desserts & Fruit' },
  garnish: { ru: 'Гарниры и овощи', uz: 'Garnir va sabzavot', en: 'Sides & Vegetables' },
};
